[package]
name = "command_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[[bin]]
name = "command_runner"
path = "src/main.rs"