name: Test_End_To_End

on:
  workflow_run:
    workflows: ["Unit_Test_And_Build"]
    types:
      - completed

jobs:
  test-images:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker images
        run: |
          docker pull kerneltzo/command_runner:main-dev
          docker pull kerneltzo/command_runner:cfssl-dev

      - name: Run test script
        run: |
          chmod +x ./tests/test_docker_images.sh
          ./tests/test_docker_images.sh
