name: Retag_And_Publish_Images

on:
  workflow_run:
    workflows: ["Test_End_To_End"]
    types:
      - completed

jobs:
  retag-publish-images:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker images
        run: |
          docker pull kerneltzo/command_runner:arm64
          docker pull kerneltzo/command_runner:amd64

      - name: Retag images
        run: |
          docker tag kerneltzo/command_runner:arm64 kerneltzo/command_runner:latest-arm64
          docker tag kerneltzo/command_runner:amd64 kerneltzo/command_runner:latest-amd64

      - name: Push retagged images
        run: |
          docker push kerneltzo/command_runner:latest-arm64
          docker push kerneltzo/command_runner:latest-amd64
